"
I am a fake test class for storing methods used as test data
"
Class {
	#name : 'DTRTDFirstFixFakeTest',
	#superclass : 'Object',
	#instVars : [
		'x'
	],
	#category : 'DrTests-RottenTestsDebugger-Tests-fixture',
	#package : 'DrTests-RottenTestsDebugger-Tests',
	#tag : 'fixture'
}

{ #category : 'tests' }
DTRTDFirstFixFakeTest >> testFirst [

	x x
]

{ #category : 'tests' }
DTRTDFirstFixFakeTest >> testSecond [

	x x y
]

{ #category : 'tests' }
DTRTDFirstFixFakeTest >> testThird [

	x x y z
]
